theme: jekyll-theme-hacker
lang: vi_VN
title: Lê Viết Hưng
description: A software engineer
logo: /images/avatar.jpg
google_analytics: UA-89654003-2
show_downloads: true
github:
  repository_url: https://github.com/vihu96
  pdf_url: /assets/pdf/Hung-resume.pdf
seo:
  name: Lê Viết Hưng
  type: Person
  links:
    https://github.com/vihu96
    https://www.viethung.info
  
